
# This file was generated by the Tkinter Designer by Parth Jadhav
#All functionality code was generated by ___________ ____
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

window = Tk()
window.geometry("396x478")
window.configure(bg = "#808080")

canvas = Canvas(
    window,
    bg = "#808080",
    height = 478,
    width = 396,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge",
)
canvas.place(x = 0, y = 0)

button_1 = Button(
    text="AC",
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)

button_2 = Button(
text="8",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_2 clicked"),
relief="flat"
)

button_3 = Button(
text="9",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_3 clicked"),
relief="flat"
)

button_4 = Button(
text="÷",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_4 clicked"),
relief="flat"
)

button_5 = Button(
text="7",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_5 clicked"),
relief="flat"
)

button_6 = Button(
text="5",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_6 clicked"),
relief="flat"
)

canvas.create_rectangle(
0.0,
0.0,
297.0,
110.0,
fill="#D28989",
outline="")



button_1.place(
x=297.0,
y=0.0,
width=99.0,
height=110.0
)

button_2.place(
x=99.0,
y=110.0,
width=99.0,
height=92.0
)


button_3.place(
x=198.0,
y=110.0,
width=99.0,
height=92.0
)

button_4.place(
x=297.0,
y=110.0,
width=99.0,
height=92.0
)


button_5.place(
x=0.0,
y=110.0,
width=99.0,
height=92.0
)


button_6.place(
x=99.0,
y=202.0,
width=99.0,
height=92.0
)

button_7 = Button(
text="6",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_7 clicked"),
relief="flat"
)
button_7.place(
x=198.0,
y=202.0,
width=99.0,
height=92.0
)

button_8 = Button(
text="X",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_8 clicked"),
relief="flat"
)
button_8.place(
x=297.0,
y=202.0,
width=99.0,
height=92.0
)

button_9 = Button(
text="4",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_9 clicked"),
relief="flat"
)
button_9.place(
x=0.0,
y=202.0,
width=99.0,
height=92.0
)

button_10 = Button(
text="2",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_10 clicked"),
relief="flat"
)
button_10.place(
x=99.0,
y=294.0,
width=99.0,
height=92.0
)

button_11 = Button(
text="3",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_11 clicked"),
relief="flat"
)
button_11.place(
x=198.0,
y=294.0,
width=99.0,
height=92.0
)

button_12 = Button(
text="-",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_12 clicked"),
relief="flat"
)
button_12.place(
x=297.0,
y=294.0,
width=99.0,
height=92.0
)

button_13 = Button(
text="1",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_13 clicked"),
relief="flat"
)
button_13.place(
x=0.0,
y=294.0,
width=99.0,
height=92.0
)

button_14 = Button(
text=".",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_14 clicked"),
relief="flat"
)
button_14.place(
x=99.0,
y=386.0,
width=99.0,
height=92.0
)

button_15 = Button(
text="=",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_15 clicked"),
relief="flat"
)
button_15.place(
x=198.0,
y=386.0,
width=99.0,
height=92.0
)

button_16 = Button(
text="+",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_16 clicked"),
relief="flat"
)
button_16.place(
x=297.0,
y=386.0,
width=99.0,
height=92.0
)

button_17 = Button(
text="0",
borderwidth=0,
highlightthickness=0,
command=lambda: print("button_17 clicked"),
relief="flat"
)
button_17.place(
x=0.0,
y=386.0,
width=99.0,
height=92.0
)

window.resizable(False, False)
window.mainloop()